version: "3.8"


services:
  app:
    build: src/main/java
    ports:
      - "8080:8080"
#    environment:
#      DB_IP: db
#      DB_NAME: quotes
#      DB_PASSWORD: 2006
#    depends_on:
#      - db
#  db:
#    image: postgres
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_PASSWORD: 2006
#      POSTGRES_USERNAME: postgres
#      POSTGRES_DB: eticket_db
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
